package main

import (
	"bytes"
	"html/template"
)

type mapParams struct {
	Name     string
	Pkg      string
	DataType string
}

func genMap(name, pkg, dataType string) ([]byte, error) {
	t := template.Must(template.New("map").Parse(`package {{.Pkg}}
	
// Code generated by dptypes. DO NOT EDIT.

type {{.Name}} struct {
	buf     []byte
	bufSize uint64
	lut     map[string]uint64
}

func New{{.Name}}() *{{.Name}} {
	return {{.Name}}{
		buf: make(buf),
		lut: make(map[string]uint64, 0),
	}
}

func (x *{{.Name}}) Set(key string, value {{.DataType}}) {

}

func (x {{.Name}}*) Get(key string) {{.DataType}}{

}
	`))

	w := bytes.NewBuffer(nil)
	p := mapParams{Name: name, Pkg: pkg, DataType: dataType}
	if err := t.Execute(w, p); err != nil {
		return []byte{}, err
	}

	return w.Bytes(), nil
}
